/*
 * SPI_Driver_Cfg.h
 *
 *  Created on: Feb 1, 2018
 *      Author: zsolt.balo
 */

#ifndef SPI_DRIVER_CFG_H_
#define SPI_DRIVER_CFG_H_

#include "SPI_Driver.h"

#define SPI_DRIVER_SPI1												OK
#define SPI_DRIVER_SPI2												NOK
#define SPI_DRIVER_SPI3												NOK


#define SPI_DRIVER_BIDIRECTIONAL_DATA_MODE_ENABLE					SPI_DRIVER_2_LINE_UNIDIRECTIONAL_DATA_FLOW
#define SPI_DRIVER_OUTPUT_ENABLE_IN_BIDIRECTIONAL_MODE				DEFAULT
#define SPI_DRIVER_CRC_CALCULATION_ENABLE							NOK
#define SPI_DRIVER_DATA_FRAME_FORMAT								SPI_DRIVER_8_BIT_DATA_FORMAT
#define SPI_DRIVER_RECEIVE_ONLY_OR_FULL_DUPLEX						SPI_DRIVER_FULL_DUPLEX
#define SPI_DRIVER_SOFTWARE_SLAVE_MANAGEMENT						OK
#define SPI_DRIVER_INETRNAL_SLAVE_SELECT							OK
#define SPI_DRIVER_FRAME_FORMAT										SPI_DRIVER_MSB_FIRST
#define SPI_DRIVER_BAUD_RATE_CONTROL								SPI_DRIVER_BAUD_RATE_DIV2
#define SPI_DRIVER_MASTER_SLAVE_SELECTION							SPI_DRIVER_MASTER_CONFIGURATION
#define SPI_DRIVER_CLOCK_POLARITY									SPI_DRIVER_CPOL_IDLE_1
#define SPI_DRIVER_CLOCK_PHASE										SPI_DRIVER_CPHA_SECOND_CLOCK_TRANSITION
#define SPI_DRIVER_SS_OUTPUT_ENABLE									NOK

#endif /* SPI_DRIVER_CFG_H_ */
