/*
 * ADC_Driver_Cfg.h
 *
 *  Created on: Jan 23, 2018
 *      Author: zsolt.balo
 */

#ifndef ADC_DRIVER_CFG_H_
#define ADC_DRIVER_CFG_H_

#include "ADC_Driver.h"

#define ADC_DRIVER_ADC1 					OK
#define ADC_DRIVER_ADC2 					NOK
#define ADC_DRIVER_ADC3 					NOK
#define ADC_DRIVER_DISCONTINUOUS_MODE 		NOK
#define ADC_DRIVER_SINGLE_CONVERSION 		OK
#define ADC_DRIVER_SCAN_MODE				NOK
#define ADC_DRIVER_TRIGGERED_INJECTION 		NOK
#define ADC_DRIVER_AUTO_INJECTION 			NOK
#define ADC_DRIVER_ANALOG_WATCHDOG 			NOK
#define ADC_DRIVER_RESOLUTION				ADC_DRIVER_RESOLUTION_12_Bits
#define ADC_DRIVER_PRESCALE 				ADC_DRIVER_PRESCALE_BY_2
#define ADC_DRIVER_ALIGNMENT				ADC_DRIVER_ALIGNMENT_RIGHT
#define ADC_DRIVER_SEQUENCE_LENGTH			ADC_DRIVER_SEQUENCE_1_CONVERSIONS
#define ADC_DRIVER_SELECTED_CHANNELS		ADC_DRIVER_SELECT_CHANNEL_1
#define ADC_DRIVER_CHANNEL_NUMBER			1

/*===UNDER CONSTRUCTION===*/

#endif /* ADC_DRIVER_CFG_H_ */
